# This is a basic workflow to help you get started with Actions

name: scrapy_info

# Controls when the workflow will run
on:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # runs at minute 50 of the 2th(UTC) hour of every day.
  - cron: "50 3,7 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      - name: 'Checkout'
        uses: actions/checkout@v2
      
      # Setup python envi
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

      # Runs a single commands using the runners shell
      - name: 'Run ./now_waqi_data_thread_action.py'
        run: python ./now_waqi_data_thread_action.py

      # github commond for check diff and commint
      - name: 'Check diff'
        run: git diff
      - name: 'Add & Commit'
        uses: EndBug/add-and-commit@v4.2.1
